<template>
  <!-- <turtleTable
    :check="true"
    :column="column"
    :tableData="tableData"
    :searchData="searchData"
  /> -->
  <div class="body">
    <Table
      ref="test"
      :checkbox="true"
      :column="column"
      :tableData="tableData"
      :searchData="searchData"
      :selectAllChange="selectAllChangeEvent"
      :selectChange="selectAllChangeEvent"
      :keyField="'expname'"
      :checkField="'expname'"
      :maxHeight="500"
      :checkRowKeys="['Exp166020']"
      :scroll="scroll"
    />
    <Table
      ref="test"
      :radio="true"
      :column="column"
      :tableData="tableData"
      :searchData="searchData"
      :keyField="'expname'"
      :maxHeight="500"
      :scroll="scroll"
    />
  </div>
</template>
<script setup>
import { ref, watch } from "vue";
import img from "./folder.png";
import Table from "./components/Table.vue";
const format = (e) => {
  const len = 6; // 固定长度
  let theNum = e + ""; // 数值
  let len2 = theNum.length; // 数值长度
  // 用0前补齐数值，达到lenNum长度
  let replaceStr = 0 + "";
  for (let j = 0; j < len - len2; j++) {
    theNum = replaceStr + theNum;
  }
  theNum = "Reagent" + theNum + "";
  return theNum;
};
const searchData = ref({
  sort: {},
  filter: [],
});
const test = ref(null);
const tableData = ref([
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152952,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp166020",
    fluid: "-",
    idx: 0,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152917,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165985",
    fluid: "-",
    idx: 1,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152916,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165984",
    fluid: "-",
    idx: 2,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152914,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165982",
    fluid: "-",
    idx: 3,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
  {
    bait: "NA",
    cellType: "-",
    description: "hsa_WT_Kidney_None(T); WTE_200ng",
    expId: 152913,
    experimentDate: "Sun, 27 Aug 2023 16:00:00 GMT",
    expname: "Exp165981",
    fluid: "-",
    idx: 4,
    instrument: "Q Exactive HF-X",
    lab: "Dr.Jun Qin Lab",
    numFraction: 1,
    numGene: 0,
    numIsoform: 0,
    numPeptide: 0,
    numRepeat: 1,
    numSpectrum: 0,
    operator: "Chen Ding",
    organ: "Kidney",
    species: "Homo sapiens (Human)",
    stage: -1,
    tissue: "Excretory system",
    type: "Profiling",
  },
]);

const column = ref([
  {
    value: "expname",
    title: "Reagent No",
    type: "format",
    format: format,
    sortable: true,
    disabled: false,
    filterType: "string",
    filterData: [{ data: "" }],
  },
  {
    value: "cellType",
    title: "Reagent Type",
    type: "link",
    icon: img,
    sortable: true,
    disabled: false,
    filterType: "string",
    filterData: [{ data: "" }],
    linkMethod: (data) => {
      linkMethod(data);
    },
  },
  {
    value: "name",
    title: "Name",
    type: "string",
    sortable: true,
    disabled: false,
    filterType: "string",
    filterData: [{ data: "" }],
  },
  {
    value: "manufacturer",
    title: "Manufacturer",
    type: "number",
    sortable: true,
    disabled: false,
    filterType: "number",
    filterData: [{ gt: "", lt: "", eq: "" }],
  },
  {
    value: "conjugate",
    title: "Conjugate",
    type: "string",
    sortable: true,
    disabled: false,
    filterType: "string",
    filterData: [{ data: "" }],
  },
  {
    value: "applications",
    title: "Applications",
    type: "tag",
    sortable: true,
    disabled: false,
    filterType: "string",
    filterData: [{ data: "" }],
  },
  {
    value: "handle",
    title: "Handle",
    type: "handle",
    buttonData: [
      {
        title: "edit",
        type: "",
      },
      {
        title: "delete",
        type: "danger",
      },
    ],
    disabled: false,
  },
]);
const selectAllChangeEvent = (checked) => {
  tableData.value = tableData.value;
  // console.log(.);
  // test.value.tableRef.setCheckboxRow(["Exp166020"], true);
  console.log();
  // console.log(checked);
};
const linkMethod = (data) => {
  console.log(data);
};
const scroll = () => {
  console.log("bottom");
};
// 监听searchData搜索
watch(searchData.value, (newValue, oldValue) => {
  // getFirmianaTableData();
  console.log(newValue);
});
</script>
<style scoped>
body {
  height: 100vh;
  width: 100vw;
}
#app {
  width: 100%;
  height: 100%;
}
.body {
  padding: 18px 8px;
  border-radius: 8px;
  background: #e6e6e6;
  margin-bottom: 20px;
  width: 1200px;
}
</style>
